---
version: "3.9"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - NAME_SERVERS=${NAME_SERVERS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${FILE1}:/config
      - ${FILE2}:/plex
    networks:
      - cloudflare
    ports:
      - 8989:8989

networks:
  cloudflare:
    external: true