---
version: "3.7"
services:
  nginx1:
    image: lscr.io/linuxserver/nginx:${TAG}
    container_name: nginx-2
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/vm/nginx/2222:/config
    restart: unless-stopped
    networks:
      - proxy

  nginx2:
    image: lscr.io/linuxserver/nginx:${TAG}
    container_name: nginx-3
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/vm/nginx/3333:/config
    restart: unless-stopped
    networks:
      - proxy

  nginx3:
    image: lscr.io/linuxserver/nginx:${TAG}
    container_name: nginx-4
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/vm/nginx/4444:/config
    restart: unless-stopped
    networks:
      - proxy   


networks:
  proxy:
    external: true