version: "3"
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
      - 8268:8268 # Example extra node port
      - 8269:8269 # Example extra node port
      - 8270:8270 # Example extra node port
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=MyInternalNode
      - nodeIP=0.0.0.0
      - nodePort=8267
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${FILE1}:/app/server
      - ${FILE2}:/app/configs
      - ${FILE3}:/app/logs
      - ${FILE4}:/media
      - ${FILE5}:/temp
  
  tdarr-node1:
    container_name: tdarr-node1
    image: ghcr.io/haveagitgat/tdarr_node
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - nodeID=NODE1
      - nodeIP=0.0.0.0
      - nodePort=8268
      - serverIP=0.0.0.0
      - serverPort=8266
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${FILE2}:/app/configs
      - ${FILE3}:/app/logs
      - ${FILE4}:/media
      - ${FILE5}:/temp
  
  tdarr-node2:
    container_name: tdarr-node2
    image: ghcr.io/haveagitgat/tdarr_node
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - nodeID=NODE2
      - nodeIP=0.0.0.0
      - nodePort=8269
      - serverIP=0.0.0.0
      - serverPort=8266
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${FILE2}:/app/configs
      - ${FILE3}:/app/logs
      - ${FILE4}:/media
      - ${FILE5}:/temp

  tdarr-node3:
    container_name: tdarr-node3
    image: ghcr.io/haveagitgat/tdarr_node
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - nodeID=NODE3
      - nodeIP=0.0.0.0
      - nodePort=8270
      - serverIP=0.0.0.0
      - serverPort=8266
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${FILE2}:/app/configs
      - ${FILE3}:/app/logs
      - ${FILE4}:/media
      - ${FILE5}:/temp