---
version: "3.9"

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - ${FILE1}:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    environment:
      - "NAME_SERVERS=${NAME_SERVERS}"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

    networks:
      - proxy

networks:
  proxy:
    external: true
