version: "3"
services:
  shepherd:
    build: .
    image: mazzolino/shepherd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SLEEP_TIME="59m"
      - ROLLBACK_ON_FAILURE="true"
    deploy:
      placement:
        constraints:
        - node.role == manager