version: "3.9"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - 'ADVERTISE_IP=https://${IP_ADDRESS}:32400/'
      - PLEX_CLAIM=${PLEX_CLAIM}
    #  - NVIDIA_VISIBLE_DEVICES=all
    #  - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    devices:
      - /dev/dri:/dev/dri
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${FILE1}:/config
      - ${FILE2}:/dev/shm
      - ${FILE3}:/media/plex
