---
version: "3"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${FILE1}:/config
      - ${FILE2}:/movies #optional
      - ${FILE3}:/tv #optional
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6767:6767