---
version: "3.9"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - "NAME_SERVERS=${NAME_SERVERS}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${FILE1}:/config
      - ${FILE2}:/plex    
    networks:
      - cloudflare
    ports:
      - 7878:7878

networks:
  cloudflare:
    external: true