---
version: '3.8'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - 'transmission:/data'
            - '${FILE1}:/downloads'
        environment:
            - OPENVPN_PROVIDER=${PROVIDER}
            - OPENVPN_CONFIG=${CONFIG}
            - OPENVPN_USERNAME=${USERNAME}
            - OPENVPN_PASSWORD=${PASSWORD}
            - LOCAL_NETWORK=${LAN_NETOWRK}
            - PUID=${PUID}
            - PGID=${PGID}
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn


volumes:
  transmission:
    external: true