version: '3.9'
services:
  factorio:
    image: factoriotools/factorio:stable
    container_name: factorio
    restart: unless-stopped
    ports:
     - "34197:34197/udp"
     - "27015:27015/tcp"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ${FILE1}:/factorio
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UPDATE_MODS_ON_START=true
      - USERNAME=${USERNAME}
      - TOKEN=${TOKEN}
      - LOAD_LATEST_SAVE=true
