version: "3.8"

services:
  linkstack:
    container_name: linkstack
    hostname: linkstack
    image: 'linkstackorg/linkstack:latest'
    environment:
      TZ: ${TZ}
      SERVER_ADMIN: ${SERVER_ADMIN}
      HTTP_SERVER_NAME: ${HTTP_SERVER_NAME}
      HTTPS_SERVER_NAME: ${HTTPS_SERVER_NAME}
      LOG_LEVEL: 'info'
      PHP_MEMORY_LIMIT: '512M'
      UPLOAD_MAX_FILESIZE: '8M'
    volumes:
      - 'linkstack:/htdocs'
    # ports:
    #  - '8190:443'
    restart: unless-stopped
    networks:
      - cloudflare

networks:
  cloudflare:
    external: true

volumes:
  linkstack: