---
version: "3.9"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${FILE1}:/config
      - ${FILE2}:/downloads
    restart: unless-stopped
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - AUTO_UPDATE=true #optional
      - NAMESERVER=${NAMESERVER}