---
version: "3.7"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=${PUID}
      - GUID=${GUID}
    volumes:
      - ${FILE1}:/config
      - ${FILE2}:/backups
      - ${FILE3}:/source
    networks:
      - proxy
    ports:
      - 8200:8200
    restart: unless-stopped

networks:
  proxy:
    external: true