version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    volumes:
      - ${FILE1}:/data/
    environment:
      - SIGNUPS_ALLOWED=false # make sure to disable this on your first build
      #- ADMIN_TOKEN=${TOKEN}  
    networks:
      - cloudflare

networks:
  cloudflare:
    external: true