version: '3.9'
services:
  orchestra:
    image: ezka77/xen-orchestra-ce
    container_name: xen-orchestra-ce
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - proxy
    ports:
      - 8002:8000
    environment:
      - DEBUG=xo:main
      - NODE_ENV=production
      - XOA_PLAN=5
    cap_add:
      - SYS_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${FILE1}:/storage
      - ${FILE2}:/run/mount/backups
    logging: &default_logging
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "2"
                
                
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - proxy
    volumes:
      - ${FILE3}:/data
    logging:
      <<: *default_logging
            
            
networks:
  proxy:
    external: true